{
  "author_association": "CONTRIBUTOR",
  "created_at": "2017-04-07T11:23:18Z",
  "assignee": null,
  "locked": false,
  "user": {
    "starred_url": "https://api.github.com/users/briandfoy/starred{/owner}{/repo}",
    "html_url": "https://github.com/briandfoy",
    "gravatar_id": "",
    "login": "briandfoy",
    "site_admin": false,
    "type": "User",
    "gists_url": "https://api.github.com/users/briandfoy/gists{/gist_id}",
    "id": 22255,
    "events_url": "https://api.github.com/users/briandfoy/events{/privacy}",
    "following_url": "https://api.github.com/users/briandfoy/following{/other_user}",
    "url": "https://api.github.com/users/briandfoy",
    "avatar_url": "https://avatars3.githubusercontent.com/u/22255?v=4",
    "node_id": "MDQ6VXNlcjIyMjU1",
    "received_events_url": "https://api.github.com/users/briandfoy/received_events",
    "repos_url": "https://api.github.com/users/briandfoy/repos",
    "organizations_url": "https://api.github.com/users/briandfoy/orgs",
    "subscriptions_url": "https://api.github.com/users/briandfoy/subscriptions",
    "followers_url": "https://api.github.com/users/briandfoy/followers"
  },
  "updated_at": "2018-06-07T09:55:42Z",
  "html_url": "https://github.com/perl6/doc/issues/1268",
  "comments_url": "https://api.github.com/repos/perl6/doc/issues/1268/comments",
  "labels_url": "https://api.github.com/repos/perl6/doc/issues/1268/labels{/name}",
  "body": "I found an exception `CX::Warn` but that doesn't show up in the [Types](https://docs.perl6.org/type.html) documentation.\r\n\r\nThis comes from my Stackoverflow question [Where should I catch a Perl 6 warning control exception?](http://stackoverflow.com/q/43243412/2766176).",
  "repository_url": "https://api.github.com/repos/perl6/doc",
  "closed_at": null,
  "comments": 2,
  "assignees": [
    
  ],
  "milestone": null,
  "state": "open",
  "id": 220186307,
  "closed_by": null,
  "labels": [
    {
      "default": false,
      "id": 244870541,
      "color": "f72bc1",
      "url": "https://api.github.com/repos/perl6/doc/labels/big",
      "node_id": "MDU6TGFiZWwyNDQ4NzA1NDE=",
      "name": "big"
    },
    {
      "default": false,
      "id": 244843225,
      "color": "5DE0FA",
      "url": "https://api.github.com/repos/perl6/doc/labels/docs",
      "node_id": "MDU6TGFiZWwyNDQ4NDMyMjU=",
      "name": "docs"
    }
  ],
  "number": 1268,
  "node_id": "MDU6SXNzdWUyMjAxODYzMDc=",
  "events_url": "https://api.github.com/repos/perl6/doc/issues/1268/events",
  "url": "https://api.github.com/repos/perl6/doc/issues/1268",
  "title": "The control exception namespace (and everything under it) is not documented"
}